language: ruby
rvm:
  - 2.0.0
  - 2.1.2
gemfile:
  - Gemfile
branches:
  only:
    - master
before_install:
  - gem uninstall --executables -i /home/travis/.rvm/gems/ruby-2.0.0-p451@global bundler
  - gem install bundler --version 1.5.2
